### ISSUE TITLE
Make Scrollview with vertical and horizontal paging

### ISSUE THREAD

**Issue by dehlen** [Ilhasoft/ISScrollViewPageSwift#12]
Hello,

Are there any plan to support a scrollview implementation with paging in both directions ? I'd like to create a scrollview which can scroll horizontally with a dynamic number of pages and scroll vertical between two pages. Is this possible with your library or do you might have an idea how to implement this behavior ?

Thanks,
David

**Comment by danielblx** [comment]
Hi!

Did you try to create an instance of ISScrollViewPage with horizontal type and within views/ viewcontrollers you add another instance of ISScrollViewPage vertical type with two views/ viewcontrollers?

**Comment by dehlen** [comment]
No I'll try this. Thanks for this suggestion.

**Comment by danielblx** [comment]
Ok! Let me know if it works.

**Comment by dehlen** [comment]
Worked like a charm. Thanks
