### ISSUE TITLE
ISScrollViewPage: wrong size of objectView

### ISSUE THREAD

**Issue by lyupko** [Ilhasoft/ISScrollViewPageSwift#16]
ISScrollViewPage doesn't change size controllers to ISScrollViewPage frame size

My solution: put it in 'func build'
objectView.frame = CGRect(origin: objectView.frame.origin, size: self.frame.size)

**Comment by danielblx** [comment]
Hi. Can you send a screenshot with layout issue and the code snippet where you setup the ScrollViewPage?

**Comment by lyupko** [comment]
Hi,

I called 'setUpScrollPageView' in viewDidLoad and self.view.updateConstraints() 

![screen shot 2016-06-22 at 3 56 19 pm](https://cloud.githubusercontent.com/assets/4130261/16267323/e3501866-3891-11e6-85b6-0455c14a7db4.png)

![screen shot 2016-06-22 at 3 52 54 pm](https://cloud.githubusercontent.com/assets/4130261/16267246/6c22501a-3891-11e6-91bc-1a4854626bf7.png)
![screen shot 2016-06-22 at 3 50 37 pm](https://cloud.githubusercontent.com/assets/4130261/16267249/6e5c081c-3891-11e6-90aa-0aac25c042e6.png)

**Comment by dielsonsales** [comment]
Have you tried calling it inside `viewDidLayoutSubviews`?

**Comment by lyupko** [comment]
yes, nothing happened

**Comment by danielblx** [comment]
Try create and setup ISScrollViewPage on viewDidLoad and in viewDidLayoutSubviews you just setup srollviewpage frame. Maybe the problem of your code is that you are initializing the ScrollViewPage on the declaration of the object.

**Comment by sagits** [comment]
Hi @danielblx, i was having the same problem. For me the issue was using a navigation bar: The scrollView Controller knows its below the navigation bar, but the page controllers didnt. 

What i done was calculating the navigation bar + status height, passing it to the page controllers and setting the frame.size.height to this size.


In ScrollViewController:

`````
func getHeight() -> CGFloat {
        let statusBarHeight = UIApplication.shared.statusBarFrame.height
        let navigationBarHeight: CGFloat = self.navigationController!.navigationBar.frame.height
        
        //    self.scrollViewPage.frame.origin.y = navigationBarHeight + statusBarHeight
        
        return self.view.frame.size.height - navigationBarHeight - statusBarHeight
    }
`````

in PageController:
`````
self.webView!.frame.size.height = parentController!.getHeight()
`````



I have done the calculations in parent because i cant access navigationController from pages.
