### ISSUE TITLE
scrollViewPageDidChanged

### ISSUE THREAD

**Issue by sagits** [Ilhasoft/ISScrollViewPageSwift#24]
Hi, the scrollViewPageDidChanged is only triggered when using goToIndex . How can i implement a function to trigger it when user change pages (swipe) ? Thanks in advance.

**Comment by danielblx** [comment]
Hey sagits! scrollViewPageDidChanged is called when scrollView is "scrolled"

**Comment by sagits** [comment]
Hi @danielblx , thanks for answering, for me it wasnt firing in any circustance. As i understand, it should be fired when i change the page, right? Its not working for me. Im currently using?


````
 self.scrollViewPage.scrollViewPageDelegate = self;


 func scrollViewPageDidScroll(_ scrollView: UIScrollView) {
        //  setNavbar(icon: self.scrollViewPage.getCurrentItem() == 1 ? .close : .plus)
 }


extension ISScrollViewPage {
    func getCurrentItem() -> Int {
        let frameWidth = Int(self.frame.width)
        let offset = self.contentOffset.x
        if (Int(offset) < frameWidth) {
            return 0
        }
        else {
            return Int(offset) / frameWidth
        }
        
    }
}
````


Im sure that getCurrentItem() works. But the scrollViewPageDidScroll is never called. May you help me pelase? Thanks in advance.

**Comment by sagits** [comment]
@danielblx I have made it work. It was my mistake: i was setting the delegate of my scrollViewPage as my ViewController on the storyboard. Thanks for helping.
